### ISSUE TITLE
Compilation fails on iOS with IL2CPP backend

### ISSUE THREAD

**Issue by seaders** [aws/aws-sdk-unity#72]
I've submitted a bug report to Unity about this as well, #704022 but I wanted to make you guys aware too.  If you try to compile to iOS with an IL2CPP backend, compilation in XCode fails.

Basically it gets the conversion of

    UnityHttpErrorResponseExceptionHandler_1_HandleException_..._gshared

wrong, doing something like,

		Object_t * L_56 = V_5;
		Object_t * L_57 = L_56;
		il2cpp_codegen_raise_exception(((Object_t *)L_57));

Down at the end of the block.

It *should* be working completely differently, or doing something like (based on what's happening in that block),

        il2cpp_codegen_raise_exception((AmazonServiceException_t61 *)L_57);

instead.

You can check it yourself with (your own project with the SDK installed), or our sample project, https://github.com/SixMinute/AWSDatasetSyncOnSuspend

**Comment by karthiksaligrama** [comment]
Thanks we are taking a look at it. could you also let us know what is the version of unity you are using?

**Comment by seaders** [comment]
Latest patch version released today, 5.0.3p1.

**Comment by akinama** [comment]
I am facing same probrem on 4.6.6p2.

**Comment by akinama** [comment]
I have realized that something is wrong with the following codes.
```
var baseServiceException = new T();
```
I have succeeded IL2CPP build by replacing as below for the time being:
```
var baseServiceException = new AmazonServiceException();
```
Please refer to the code.
https://github.com/aws/aws-sdk-unity/blob/master/Assets/AWSSDK/src/Core/Amazon.Runtime/Pipeline/ErrorHandler/_unity/UnityHttpErrorResponseExceptionHandler.cs#L98

**Comment by karthiksaligrama** [comment]
@akinama we wouldn't want to change the typed exception to the base exception, because there are different workflow which gets kicked off based on the exception type.

**Comment by akinama** [comment]
@karthiksaligrama Off course, I think so too. Are there some IL2CPP bugs at that line?

**Comment by androidsauce** [comment]
I am also getting this on Unity 5.1.1f1

**Comment by seaders** [comment]
Any update on this?  @karthiksaligrama no chance you also got in touch with Unity about this?  I logged the bug#, 704022 and it'd be great if you guys could jump in with requesting this to be fixed.

**Comment by karthiksaligrama** [comment]
@seaders  i'm unable to find the bug on their issue tracker can you paste the complete url here?

**Comment by seaders** [comment]
Unfortunately, despite the fact that I checked the "Public" box, it hasn't shown up there, so the only URL I have is to our internal company one, which I can't share publicly, sorry.

Do you guys not have any Unity contacts to be able to contact directly?

**Comment by karthiksaligrama** [comment]
i just needed it to reference the bug to them. But that's ok. i'll try to reproduce the problem and send them another bug report.

**Comment by seaders** [comment]
If you're on IRC (#unity3d), main guy who's been a great help to us is Tak there.  He's one of their iOS debugging team, not necessarily IL2CPP, but iOS nonetheless and he has escalated some of the issues we've had (with the AWS library, and other things) already.

fyi

**Comment by karthiksaligrama** [comment]
is it possible for you guys to fall back on 5.0.1p3. I just tested it on that version and seems to be working. In the meantime i'll see if we can circumvent this problem in the sdk as well.

**Comment by seaders** [comment]
Unfortunately not, no.  There was another IL2CPP bug to do with compilation trying to reference Unity Editor code despite it being compiler defined out which meant you couldn't even build the XCode project.  That got fixed in the 5.0.3p1 release, along with a few other IL2CPP bugs (but obviously they could well have brought some of this in).

**Comment by benbritten** [comment]
Hello! Yeah, we have come up hard against this bug as well. We need 5.1.1 for other various reasons, but not being able to build to iOS is killing us at the moment.  We are looking at maybe rolling back the AWS SDK to the last version which is also not ideal as we want to be able to use the new stuff. I know this is probably ultimately a problem with Unity's IL2CPP code gen; but if there is something that can be done at the SDK level that would be great.

**Comment by karthiksaligrama** [comment]
@benbritten at the moment you can follow the fix mentiond by @akinama https://github.com/aws/aws-sdk-unity/issues/72#issuecomment-112296299

**Comment by benbritten** [comment]
@karthiksaligrama Ok great, thanks for that! We did look at that but were a bit leery as you had mentioned that there may be some downstream issues, but if it is safe enough for now and gets us back on track then I will take it!

**Comment by 5argon** [comment]
Today this bug still exist, but thanks to @akinama that the fix works.

**Comment by karthiksaligrama** [comment]
temporarily updated the sdk as per @akinama fix until unity fixes this bug on their end
